### ISSUE TITLE
add record fail when field with `l10n:"sync"`

### ISSUE THREAD

**Issue by oonxt** [qor/slug#4]
in slug.tmpl
change
{{if not (has_update_permission .Meta)}}disabled{{end}}
to
{{if not (has_update_permission .Meta)}}readonly{{end}}
may be more reasonable.

**Comment by jinzhu** [comment]
Hi @oonxt 

I think it should be fine? as we will save with the slug from default locale.

**Comment by oonxt** [comment]
the form won't submit the disabled field data, then return a error because the slug field is null.

or may be I missed something ....
